services:
  backend-e-commerce:
    build:
      context: .
    container_name: backend-e-commerce
    depends_on:
      - database-e-commerce
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-e-commerce:5432/ecommercebackend
    ports:
      - "8083:8083"
    volumes:
      - /var/www/upload:/var/www/upload
    networks:
      - mynetwork

  database-e-commerce:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    container_name: database-e-commerce
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommercebackend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 🔥 Kalıcı veri deposu ekledik
    networks:
      - mynetwork

  redis-e-commerce:
    image: redis:alpine
    container_name: redis-e-commerce
    ports:
      - "6379:6379"
    networks:
      - mynetwork


volumes:
  postgres_data:  # 🔥 Postgres için kalıcı veri deposu
  upload-data:


networks:
  mynetwork:
    driver: bridge
