spring:
  application:
    name: e-commerce-basic

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB


  # Datasource Configuration (Veritabanı Bağlantısı)
  datasource:
    url: ${GULCE_DB_URL}
    username: ${GULCE_DB_USERNAME}
    password: ${GULCE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  # JPA Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${GULCE_REDIS_HOST}
      port: ${GULCE_REDIS_PORT}
      database: 0

logging:
  pattern:
    console: ${GULCE_LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${GULCE_SPRING_SECURITY_LOG_LEVEL}

upload:
  file:
    dir: ${GULCE_UPLOAD_FILE_DIR}
    url: ${GULCE_UPLOAD_FILE_URL}
    product:
      size: 104857600

cookie:
  refreshTokenCookie:
    secure: ${GULCE_REFRESH_TOKEN_SECURE}
    refreshmaxAge: ${GULCE_REFRESH_TOKEN_MAX_AGE}
    sameSite: ${GULCE_REFRESH_TOKEN_SAME_SITE}
    path: /api/v1/auth

jwt:
  accessExp: ${GULCE_JWT_ACCESS_EXP}
  refreshAge: ${GULCE_JWT_REFRESH_AGE}
  secret: ${GULCE_JWT_SECRET}
  jwtheader: Authorization

regex:
  email: ${GULCE_REGEX_EMAIL}
  password: ${GULCE_REGEX_PASSWORD}

payment:
  iyzico:
    apiKey: ${GULCE_IYZICO_API_KEY}
    secretKey: ${GULCE_IYZICO_SECRET_KEY}
    baseUrl: ${GULCE_IYZICO_BASE_URL}
    callBack: /api/v1/payment/payCallBack

domain:
  test: ${GULCE_DOMAIN_TEST}
  name: ${GULCE_DOMAIN_NAME}
  namewww: ${GULCE_DOMAIN_NAMEWWW}
  geliver: ${GULCE_DOMAIN_GELIVER}

geliver:
  cargo:
    test: ${GULCE_GELIVER_CARGO_TEST}
    key: ${GULCE_GELIVER_CARGO_KEY}

server:
  port: ${GULCE_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/actuator

mailgun:
  key: ${GULCE_MAILGUN_KEY}

sendgrid:
  api-key: ${GULCE_SENDGRID_API_KEY}