spring:
  application:
    name: e-commerce-basic

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommercebackend}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

upload:
  file:
    dir: ${UPLOAD_FILE_DIR:/var/www/html/projects/ecommerce/images/}
    url: ${UPLOAD_FILE_URL:https://litysofttest1.site/api/v1/upload/}
    product:
      size: 104857600

cookie:
  refreshTokenCookie:
    secure: ${REFRESH_TOKEN_COOKIE_SECURE:true}
    refreshmaxAge: ${REFRESH_TOKEN_COOKIE_REFRESH_MAX_AGE:604800}
    sameSite: ${REFRESH_TOKEN_COOKIE_SAME_SITE:Strict}
    path: ${REFRESH_TOKEN_COOKIE_PATH:/api/v1/auth}

jwt:
  accessExp: ${JWT_ACCESS_EXP:900000}
  refreshAge: ${JWT_REFRESH_AGE:604800000}
  secret: ${JWT_SECRET:C2VB987vxNVXvn543xVvxmVX7BCVM432NxvbvbnVXncm}
  jwtheader: ${JWT_HEADER:Authorization}

regex:
  email: ^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
  password: ^(?=.*[A-Z]).{8,}$

payment:
  iyzico:
    apiKey: ${IYZICO_API_KEY:sandbox-JbYzNd3TVSGRKgrKKFiM5Ha7MJP7YZSo}
    secretKey: ${IYZICO_SECRET_KEY:sandbox-mvXUSAUVAUhj7pNFFsbrKvWjGL5cEaUP}
    baseUrl: ${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}
    callBack: /api/v1/payment/payCallBack

domain:
  test: ${DOMAIN_TEST:https://litysofttest1.site}
  name: ${DOMAIN_NAME:https://litysofttest1.site}
  namewww: ${DOMAIN_NAMEWWW:https://www.litysofttest1.site}
  geliver: ${DOMAIN_GELIVER:https://api.geliver.io/api/v1}

geliver:
  cargo:
    test: ${GELIVER_CARGO_TEST:true}
    key: ${GELIVER:f0818afa-0027-41c2-b985-ef135ea30dd9}

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/actuator
