spring:
  application:
    name: e-commerce-basic

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL}

upload:
  file:
    dir: ${UPLOAD_FILE_DIR}
    url: ${UPLOAD_FILE_URL}
    product:
      size: 104857600

cookie:
  refreshTokenCookie:
    secure: ${REFRESH_TOKEN_COOKIE_SECURE}
    refreshmaxAge: ${REFRESH_TOKEN_COOKIE_REFRESH_MAX_AGE}
    sameSite: ${REFRESH_TOKEN_COOKIE_SAME_SITE}
    path: ${REFRESH_TOKEN_COOKIE_PATH}

jwt:
  accessExp: ${JWT_ACCESS_EXP}
  refreshAge: ${JWT_REFRESH_AGE}
  secret: ${JWT_SECRET}
  jwtheader: ${JWT_HEADER}

regex:
  email: ^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
  password: ^(?=.*[A-Z]).{8,}$

payment:
  iyzico:
    apiKey: ${IYZICO_API_KEY}
    secretKey: ${IYZICO_SECRET_KEY}
    baseUrl: ${IYZICO_BASE_URL}
    callBack: /api/v1/payment/payCallBack

domain:
  test: ${DOMAIN_TEST}
  name: ${DOMAIN_NAME}
  namewww: ${DOMAIN_NAMEWWW}
  geliver: ${DOMAIN_GELIVER}

geliver:
  cargo:
    test: ${GELIVER_CARGO_TEST}
    key: ${GELIVER}

server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/actuator
