global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecommerce metrics'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['backend-e-commerce:8083']
        labels:
          application: 'My Spring Boot Application'