name: CI/CD for Backend

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy_backend:
    runs-on: ubuntu-latest

    steps:

      - name: Setup SSH Key for Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 141.11.109.132
          username: root
          key: ${{ secrets.ECOMMERCESECRET }}
          script: |
            cd /home/ecommerce/proje1/e-commerce-backend
            sudo systemctl stop proje1.service || true
            rm -rf target/
            git pull
            mvn clean package -DskipTests
            sudo systemctl start proje1.service
            sudo systemctl status proje1.service